version: '3.8'

networks:
  laravel:
    name: laravel

services:
  nginx:
    build:
      context: .
      dockerfile: Docker/nginx.dockerfile
    container_name: nginx
    depends_on:
      - php
      - mysql
      - redis
    ports:
      - 80
      - 443:443
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Docker/php.dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:5.7.32
    container_name: mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    volumes:
      - ./Docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Docker/php.dockerfile
    container_name: artisan
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - laravel

  phpunit:
    build:
      context: .
      dockerfile: Docker/php.dockerfile
    container_name: phpunit
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/var/www/html/vendor/bin/phpunit"]
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: Docker/php.dockerfile
    container_name: scheduler
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan", "schedule:work"]
    networks:
      - laravel